import Link from 'next/link'
import { ArrowRight, Check, Sparkles } from 'lucide-react'
import SiteHeader from './site-header'

export type ServicePageData = { title: string; eyebrow: string; intro: string; bullets: string[]; outcomes: string[]; accent?: string }

export default function ServicePage({ data }: { data: ServicePageData }) {
  return <main className="min-h-screen bg-[#f7f9fc] text-[#102238]"><SiteHeader /><section className="mx-auto max-w-7xl px-5 pb-16 pt-36 lg:px-8 lg:pb-24 lg:pt-44"><div className="max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white px-3 py-2 text-xs font-bold uppercase tracking-[0.18em] text-[#087ff5]"><Sparkles className="h-3.5 w-3.5" /> Info Edge services</div><p className="mt-8 text-sm font-bold uppercase tracking-[0.2em] text-[#087ff5]">{data.eyebrow}</p><h1 className="mt-4 text-5xl font-black leading-[1.04] tracking-[-0.055em] sm:text-6xl">{data.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#617087]">{data.intro}</p><Link href="/contact#query" className="mt-9 inline-flex rounded-full bg-[#087ff5] px-7 py-4 font-bold text-white shadow-xl shadow-blue-500/20 transition hover:-translate-y-1 hover:bg-[#0669d2]">Discuss your goals <ArrowRight className="ml-2 h-4 w-4" /></Link></div></section><section className="bg-white px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#087ff5]">What we deliver</p><h2 className="mt-4 text-3xl font-black">A focused service built around your next milestone.</h2><div className="mt-8 space-y-4">{data.bullets.map((item) => <div key={item} className="flex gap-3 rounded-2xl border border-slate-100 bg-[#f9fbfe] p-4"><Check className="mt-0.5 h-5 w-5 shrink-0 text-[#087ff5]" /><span className="leading-7 text-[#536278]">{item}</span></div>)}</div></div><div className="rounded-[2rem] bg-[#102238] p-8 text-white"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#5bb1ff]">The outcome</p><h2 className="mt-4 text-3xl font-black">More visibility. Better action.</h2><div className="mt-8 space-y-5">{data.outcomes.map((item) => <div key={item} className="border-b border-white/10 pb-5 text-lg text-blue-100/80">{item}</div>)}</div></div></div></section><section className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl rounded-[2rem] bg-blue-50 p-8 text-center sm:p-12"><h2 className="text-3xl font-black">Ready to make your brand impossible to miss?</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-[#617087]">Tell us what you are working toward and we will recommend the right mix of channels.</p><Link href="/contact#query" className="mt-7 inline-flex rounded-full bg-[#087ff5] px-7 py-4 font-bold text-white">Send an enquiry <ArrowRight className="ml-2 h-4 w-4" /></Link></div></section></main>
}
